import { ClerkProvider } from '@clerk/nextjs';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { geistMono, geistSans } from '../assets/fonts';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Healthcare System',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={'/'}>
      <html lang='en'>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
          <Toaster richColors position='top-center' />
        </body>
      </html>
    </ClerkProvider>
  );
}
